/**
 * CV Block Types
 *
 * Represents structured CV sections (blocks) generated by AI.
 * Each block has a type, optional title, content, and optional experienceId.
 *
 * @see docs/AI_Interaction_Contract.md - Operation 11 (generateCvBlocks)
 */

export type SectionType =
  | 'summary'
  | 'experience'
  | 'education'
  | 'skills'
  | 'languages'
  | 'certifications'
  | 'interests'
  | 'custom';

export interface CVSection {
  type: SectionType;
  title?: string | null;
  content: string;
  experienceId?: string | null;
}

export interface CVBlocksResult {
  sections: CVSection[];
}

export interface UserProfileInput {
  id: string;
  fullName: string;
  headline?: string;
  location?: string;
  seniorityLevel?: string;
  goals?: string[];
  aspirations?: string[];
  personalValues?: string[];
  strengths?: string[];
}

export interface ExperienceInput {
  id: string;
  title: string;
  company: string;
  startDate?: string;
  endDate?: string;
  location?: string;
  responsibilities?: string[];
  tasks?: string[];
}

export interface StoryInput {
  experienceId: string;
  situation: string;
  task: string;
  action: string;
  result: string;
  achievements?: string[];
  kpiSuggestions?: string[];
}

export interface GenerateCvBlocksInput {
  userProfile: UserProfileInput;
  selectedExperiences: ExperienceInput[];
  stories?: StoryInput[];
  skills?: string[];
  languages?: string[];
  certifications?: string[];
  interests?: string[];
  sectionsToGenerate?: SectionType[];
  jobDescription?: string | null;
}
